import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SearchBar from "./components/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ERP - Gestion cadena de valor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#F1F2F5] ${inter.className} h-screen`}>
        <header>
          <SearchBar/>
          <Navbar />
        </header>
        <main className="flex justify-center">{children}</main>
      </body>
    </html>
  );
}
